version: "3.9"
services:
  products:api:
    build: ./ing_products
    image: postgres:latest
    environment:
    - "SPRING_PROFILES_ACTIVE=dev"
    - "SERVER_PORT=8090"
    - "SPRING_DATASOURCE_USERNAME=root"
    - "SPRING_DATASOURCE_PASSWORD=secret"
    - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ing_products"
    ports:
    - "8090:8090"
    depends_on:
    - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: ing_products