spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ing_products
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    default-schema: public
    locations: classpath:db/migration,classpath:db/seed
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true