spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ing_products
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    default-schema: public
    out-of-order: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tagsSorter: alpha
      operationsSorter: alpha
    api-docs:
      enabled: true